@baseUrl=http://127.0.0.1:3456


### get balance

# @name balance
GET {{baseUrl}}/balance/xopt/UQCGAdFrKHV0a_FahdCqILB-tiVJ3EqXC1TWnnLCKq_aTFvi


### send tokens

# @name send
POST {{baseUrl}}/send/EQCxE6mUtQJKFnGfaROTKOt1lZbDiiX1kCixRv7Nw2Id_sDs
Content-Type: application/json

{
    "address": "0:3b272e4bf3865de89cab22c2c740dd03a35c250b2426f73127d084a5a3c12fee",
    "amount": "1"
}